"""
AeroScientia — Bilingual Aerospace Glossary
============================================
Glosario técnico bilingüe EN↔ES para el dominio aeroespacial.
Curado manualmente + expandible con el extractor NLP automático.

Estructura de cada entrada:
{
    "en": "Technical term in English",
    "es": "Término técnico en español",
    "domain": "aeronautics | astrodynamics | propulsion | materials | avionics",
    "entity_type": "EQUATION | PARAMETER | PHYSICAL_LAW | ...",
    "definition_en": "Technical definition in English",
    "definition_es": "Definición técnica en español",
    "symbol": "Variable symbol if applicable",
    "unit": "SI unit if applicable",
    "related": ["list", "of", "related", "terms"]
}
"""

GLOSSARY = [

    # ══════════════════════════════════════════════════════════
    # AERODYNAMIC FORCES — FUERZAS AERODINÁMICAS
    # ══════════════════════════════════════════════════════════
    {
        "en": "Lift",
        "es": "Sustentación",
        "domain": "aeronautics",
        "entity_type": "FORCE",
        "definition_en": "Aerodynamic force perpendicular to the freestream velocity vector, generated by pressure differential over the airfoil.",
        "definition_es": "Fuerza aerodinámica perpendicular al vector de velocidad de vuelo libre, generada por el diferencial de presión sobre el perfil alar.",
        "symbol": "L",
        "unit": "N",
        "related": ["Lift Coefficient", "Angle of Attack", "Airfoil", "Bernoulli's Principle"]
    },
    {
        "en": "Drag",
        "es": "Resistencia aerodinámica / Arrastre",
        "domain": "aeronautics",
        "entity_type": "FORCE",
        "definition_en": "Aerodynamic force opposing the direction of motion, composed of parasitic drag and induced drag.",
        "definition_es": "Fuerza aerodinámica que se opone al movimiento, compuesta por resistencia parásita y resistencia inducida.",
        "symbol": "D",
        "unit": "N",
        "related": ["Parasitic Drag", "Induced Drag", "Drag Coefficient", "Lift-to-Drag Ratio"]
    },
    {
        "en": "Thrust",
        "es": "Empuje",
        "domain": "aeronautics",
        "entity_type": "FORCE",
        "definition_en": "Propulsive force generated by the engine, equal to mass flow rate times exhaust velocity by Newton's Third Law.",
        "definition_es": "Fuerza propulsora generada por el motor, igual al gasto másico multiplicado por la velocidad de salida según la Tercera Ley de Newton.",
        "symbol": "T",
        "unit": "N",
        "related": ["Specific Impulse", "Mass Flow Rate", "Newton's Third Law", "Turbofan"]
    },
    {
        "en": "Weight",
        "es": "Peso",
        "domain": "aeronautics",
        "entity_type": "FORCE",
        "definition_en": "Gravitational force acting on the aircraft, equal to mass times gravitational acceleration.",
        "definition_es": "Fuerza gravitatoria que actúa sobre la aeronave, igual a la masa por la aceleración gravitacional.",
        "symbol": "W",
        "unit": "N",
        "related": ["Lift", "Mass", "Gravitational Acceleration", "Wing Loading"]
    },
    {
        "en": "Parasitic Drag",
        "es": "Resistencia Parásita",
        "domain": "aeronautics",
        "entity_type": "FORCE",
        "definition_en": "Drag not associated with lift production, including skin friction drag and form drag. Increases with velocity squared.",
        "definition_es": "Resistencia no asociada a la generación de sustentación, incluyendo la fricción de piel y la resistencia de forma. Aumenta con el cuadrado de la velocidad.",
        "symbol": "D_p",
        "unit": "N",
        "related": ["Induced Drag", "Skin Friction", "Form Drag", "Reynolds Number"]
    },
    {
        "en": "Induced Drag",
        "es": "Resistencia Inducida",
        "domain": "aeronautics",
        "entity_type": "FORCE",
        "definition_en": "Drag generated as a byproduct of lift production, caused by wingtip vortices. Decreases with velocity squared.",
        "definition_es": "Resistencia generada como subproducto de la sustentación, causada por vórtices de punta de ala. Disminuye con el cuadrado de la velocidad.",
        "symbol": "D_i",
        "unit": "N",
        "related": ["Wingtip Vortices", "Aspect Ratio", "Oswald Efficiency Factor", "Lift"]
    },

    # ══════════════════════════════════════════════════════════
    # AERODYNAMIC PARAMETERS — PARÁMETROS AERODINÁMICOS
    # ══════════════════════════════════════════════════════════
    {
        "en": "Lift Coefficient",
        "es": "Coeficiente de Sustentación",
        "domain": "aeronautics",
        "entity_type": "PARAMETER",
        "definition_en": "Dimensionless number that quantifies the lift generated by an airfoil relative to dynamic pressure and wing area. Dependent on angle of attack and airfoil geometry.",
        "definition_es": "Número adimensional que cuantifica la sustentación generada por un perfil alar en relación a la presión dinámica y la superficie alar. Depende del ángulo de ataque y la geometría del perfil.",
        "symbol": "CL",
        "unit": "dimensionless",
        "related": ["Lift Equation", "Angle of Attack", "Stall", "Airfoil"]
    },
    {
        "en": "Drag Coefficient",
        "es": "Coeficiente de Resistencia",
        "domain": "aeronautics",
        "entity_type": "PARAMETER",
        "definition_en": "Dimensionless number quantifying aerodynamic resistance relative to dynamic pressure and reference area.",
        "definition_es": "Número adimensional que cuantifica la resistencia aerodinámica en relación a la presión dinámica y el área de referencia.",
        "symbol": "CD",
        "unit": "dimensionless",
        "related": ["Drag Polar", "Oswald Efficiency", "Parasitic Drag", "Induced Drag"]
    },
    {
        "en": "Angle of Attack",
        "es": "Ángulo de Ataque",
        "domain": "aeronautics",
        "entity_type": "PARAMETER",
        "definition_en": "Angle between the airfoil chord line and the relative wind vector. Critical parameter controlling lift coefficient and stall behavior.",
        "definition_es": "Ángulo entre la cuerda del perfil alar y el vector de velocidad del viento relativo. Parámetro crítico que controla el coeficiente de sustentación y el comportamiento de entrada en pérdida.",
        "symbol": "α (alpha)",
        "unit": "degrees / radians",
        "related": ["Lift Coefficient", "Stall", "Critical Angle", "Pitch Attitude"]
    },
    {
        "en": "Mach Number",
        "es": "Número de Mach",
        "domain": "aeronautics",
        "entity_type": "PARAMETER",
        "definition_en": "Ratio of flow velocity to the local speed of sound. Defines flight regimes: subsonic (M<0.8), transonic (0.8-1.2), supersonic (1.2-5), hypersonic (M>5).",
        "definition_es": "Relación entre la velocidad del flujo y la velocidad local del sonido. Define los regímenes de vuelo: subsónico (M<0.8), transónico (0.8-1.2), supersónico (1.2-5), hipersónico (M>5).",
        "symbol": "M",
        "unit": "dimensionless",
        "related": ["Speed of Sound", "Shock Wave", "Critical Mach", "Transonic Flight"]
    },
    {
        "en": "Reynolds Number",
        "es": "Número de Reynolds",
        "domain": "aeronautics",
        "entity_type": "PARAMETER",
        "definition_en": "Dimensionless ratio of inertial forces to viscous forces in a flow. Determines whether flow is laminar or turbulent.",
        "definition_es": "Relación adimensional entre las fuerzas de inercia y las fuerzas viscosas en un flujo. Determina si el flujo es laminar o turbulento.",
        "symbol": "Re",
        "unit": "dimensionless",
        "related": ["Boundary Layer", "Laminar Flow", "Turbulent Flow", "Navier-Stokes"]
    },
    {
        "en": "Aspect Ratio",
        "es": "Alargamiento Alar",
        "domain": "aeronautics",
        "entity_type": "PARAMETER",
        "definition_en": "Ratio of wing span squared to wing area (b²/S). High aspect ratio wings (gliders) minimize induced drag; low AR wings favor high-speed maneuverability.",
        "definition_es": "Relación entre el cuadrado de la envergadura y la superficie alar (b²/S). Alas de alto alargamiento (planeadores) minimizan la resistencia inducida; bajo AR favorece la maniobrabilidad a alta velocidad.",
        "symbol": "AR",
        "unit": "dimensionless",
        "related": ["Induced Drag", "Oswald Efficiency Factor", "Wing Span", "Glider"]
    },
    {
        "en": "Wing Loading",
        "es": "Carga Alar",
        "domain": "aeronautics",
        "entity_type": "PARAMETER",
        "definition_en": "Ratio of aircraft weight to wing area. Determines stall speed, maneuverability, and ride quality in turbulence.",
        "definition_es": "Relación entre el peso de la aeronave y la superficie alar. Determina la velocidad de entrada en pérdida, la maniobrabilidad y la calidad de vuelo en turbulencia.",
        "symbol": "W/S",
        "unit": "N/m²",
        "related": ["Stall Speed", "Maneuverability", "Lift", "Wing Area"]
    },

    # ══════════════════════════════════════════════════════════
    # PHYSICAL LAWS — LEYES FÍSICAS
    # ══════════════════════════════════════════════════════════
    {
        "en": "Bernoulli's Principle",
        "es": "Principio de Bernoulli",
        "domain": "aeronautics",
        "entity_type": "PHYSICAL_LAW",
        "definition_en": "In steady flow, an increase in fluid velocity results in a decrease in static pressure. Basis for airfoil lift generation.",
        "definition_es": "En flujo estacionario, un aumento en la velocidad del fluido resulta en una disminución de la presión estática. Base para la generación de sustentación en perfiles alares.",
        "symbol": "P + ½ρv² = constant",
        "unit": "Pa",
        "related": ["Lift", "Dynamic Pressure", "Static Pressure", "Airfoil", "Venturi Effect"]
    },
    {
        "en": "Newton's Third Law",
        "es": "Tercera Ley de Newton",
        "domain": "aeronautics",
        "entity_type": "PHYSICAL_LAW",
        "definition_en": "For every action there is an equal and opposite reaction. Explains downwash-induced lift and jet engine thrust generation.",
        "definition_es": "A toda acción corresponde una reacción igual y opuesta. Explica la sustentación por deflexión hacia abajo (downwash) y la generación de empuje en motores de reacción.",
        "symbol": "F₁₂ = -F₂₁",
        "unit": "N",
        "related": ["Lift", "Thrust", "Downwash", "Jet Engine", "Momentum"]
    },
    {
        "en": "Navier-Stokes Equations",
        "es": "Ecuaciones de Navier-Stokes",
        "domain": "aeronautics",
        "entity_type": "EQUATION",
        "definition_en": "Partial differential equations describing the motion of viscous fluid substances. The 'Holy Grail' of aerodynamics; used in CFD to model turbulence and complex flow.",
        "definition_es": "Ecuaciones diferenciales parciales que describen el movimiento de sustancias fluidas viscosas. El 'Santo Grial' de la aerodinámica; utilizadas en CFD para modelar turbulencias y flujos complejos.",
        "symbol": "ρ(∂v/∂t + v·∇v) = -∇P + μ∇²v + f",
        "unit": "Pa/m",
        "related": ["CFD", "Turbulence", "Reynolds Number", "Viscosity", "Boundary Layer"]
    },
    {
        "en": "Continuity Equation",
        "es": "Ecuación de Continuidad",
        "domain": "aeronautics",
        "entity_type": "EQUATION",
        "definition_en": "Conservation of mass in fluid flow: mass flow rate is constant in steady state. As cross-section decreases, velocity increases.",
        "definition_es": "Conservación de masa en el flujo de fluidos: el gasto másico es constante en estado estacionario. Al reducirse la sección transversal, la velocidad aumenta.",
        "symbol": "ρ₁A₁v₁ = ρ₂A₂v₂",
        "unit": "kg/s",
        "related": ["Mass Flow Rate", "Nozzle Design", "Venturi", "Compressible Flow"]
    },

    # ══════════════════════════════════════════════════════════
    # AIRFOIL & COMPONENTS — PERFIL ALAR Y COMPONENTES
    # ══════════════════════════════════════════════════════════
    {
        "en": "Airfoil",
        "es": "Perfil Alar",
        "domain": "aeronautics",
        "entity_type": "COMPONENT",
        "definition_en": "Cross-sectional shape of a wing designed to generate lift. Characterized by chord length, thickness distribution, camber, and leading/trailing edge geometry.",
        "definition_es": "Forma de la sección transversal de un ala diseñada para generar sustentación. Caracterizada por la cuerda, distribución de espesor, curvatura y geometría del borde de ataque/salida.",
        "symbol": "—",
        "unit": "—",
        "related": ["Chord", "Camber", "Leading Edge", "Trailing Edge", "NACA Series"]
    },
    {
        "en": "Extrados",
        "es": "Extradós",
        "domain": "aeronautics",
        "entity_type": "COMPONENT",
        "definition_en": "Upper surface of an airfoil where flow accelerates, creating lower static pressure that contributes to lift.",
        "definition_es": "Superficie superior del perfil alar donde el flujo se acelera, creando menor presión estática que contribuye a la sustentación.",
        "symbol": "—",
        "unit": "—",
        "related": ["Intrados", "Bernoulli's Principle", "Static Pressure", "Lift"]
    },
    {
        "en": "Stall",
        "es": "Entrada en Pérdida / Pérdida Aerodinámica",
        "domain": "aeronautics",
        "entity_type": "FLIGHT_PHENOMENON",
        "definition_en": "Condition where angle of attack exceeds the critical value, causing flow separation over the upper surface, sharp decrease in CL and increase in CD.",
        "definition_es": "Condición en que el ángulo de ataque supera el valor crítico, causando separación del flujo sobre el extradós, caída brusca del CL y aumento del CD.",
        "symbol": "α_crit",
        "unit": "degrees",
        "related": ["Critical Angle of Attack", "Lift Coefficient", "Flow Separation", "Recovery"]
    },

    # ══════════════════════════════════════════════════════════
    # ASTRODYNAMICS — ASTRODINÁMICA
    # ══════════════════════════════════════════════════════════
    {
        "en": "Delta-v",
        "es": "Delta-v / Variación de Velocidad",
        "domain": "astrodynamics",
        "entity_type": "PARAMETER",
        "definition_en": "Measure of the impulse needed to perform orbital maneuvers. The 'currency' of spaceflight. Total available Δv determines mission capability.",
        "definition_es": "Medida del impulso necesario para realizar maniobras orbitales. La 'moneda' del vuelo espacial. El Δv total disponible determina la capacidad de la misión.",
        "symbol": "Δv",
        "unit": "m/s or km/s",
        "related": ["Tsiolkovsky Equation", "Hohmann Transfer", "Specific Impulse", "Propellant Mass"]
    },
    {
        "en": "Specific Impulse",
        "es": "Impulso Específico",
        "domain": "astrodynamics",
        "entity_type": "PARAMETER",
        "definition_en": "Measure of propulsion efficiency; thrust produced per unit weight flow of propellant per second. The higher the Isp, the more efficient the engine.",
        "definition_es": "Medida de la eficiencia de propulsión; empuje producido por unidad de flujo de peso del propelente por segundo. Mayor Isp indica mayor eficiencia del motor.",
        "symbol": "Isp",
        "unit": "seconds",
        "related": ["Rocket Equation", "Exhaust Velocity", "Thrust", "Propellant Efficiency"]
    },
    {
        "en": "Tsiolkovsky Rocket Equation",
        "es": "Ecuación del Cohete de Tsiolkovski",
        "domain": "astrodynamics",
        "entity_type": "EQUATION",
        "definition_en": "Fundamental equation of rocket propulsion relating achievable Δv to exhaust velocity and propellant mass fraction.",
        "definition_es": "Ecuación fundamental de la propulsión espacial que relaciona el Δv alcanzable con la velocidad de escape y la fracción de masa de propelente.",
        "symbol": "Δv = ve · ln(m₀/mf)",
        "unit": "m/s",
        "related": ["Specific Impulse", "Mass Ratio", "Delta-v", "Exhaust Velocity"]
    },
    {
        "en": "Hohmann Transfer Orbit",
        "es": "Órbita de Transferencia de Hohmann",
        "domain": "astrodynamics",
        "entity_type": "MANEUVER",
        "definition_en": "Minimum-energy elliptical orbit used to transfer between two coplanar circular orbits using two engine burns.",
        "definition_es": "Órbita elíptica de mínima energía utilizada para transferir entre dos órbitas circulares coplanares usando dos quemados de motor.",
        "symbol": "—",
        "unit": "—",
        "related": ["Delta-v", "Apoapsis", "Periapsis", "Orbital Mechanics", "Elliptical Orbit"]
    },
    {
        "en": "Kepler's Laws",
        "es": "Leyes de Kepler",
        "domain": "astrodynamics",
        "entity_type": "PHYSICAL_LAW",
        "definition_en": "Three laws governing planetary and satellite motion: (1) orbits are ellipses, (2) equal areas in equal times, (3) T² proportional to a³.",
        "definition_es": "Tres leyes que gobiernan el movimiento planetario y de satélites: (1) las órbitas son elipses, (2) áreas iguales en tiempos iguales, (3) T² proporcional a a³.",
        "symbol": "T² = (4π²/GM) · a³",
        "unit": "—",
        "related": ["Orbital Period", "Semi-Major Axis", "Eccentricity", "Orbital Mechanics"]
    },
    {
        "en": "Low Earth Orbit",
        "es": "Órbita Terrestre Baja",
        "domain": "astrodynamics",
        "entity_type": "ORBIT_TYPE",
        "definition_en": "Orbital regime between 160-2,000 km altitude. Orbital period ~90-127 min. Location of ISS (408 km). High atmospheric drag requires periodic reboosting.",
        "definition_es": "Régimen orbital entre 160-2.000 km de altitud. Período orbital ~90-127 min. Ubicación de la ISS (408 km). El alto arrastre atmosférico requiere relanzamientos periódicos.",
        "symbol": "LEO",
        "unit": "km altitude",
        "related": ["Geostationary Orbit", "ISS", "Orbital Velocity", "Atmospheric Drag"]
    },
    {
        "en": "Orbital Velocity",
        "es": "Velocidad Orbital",
        "domain": "astrodynamics",
        "entity_type": "PARAMETER",
        "definition_en": "Tangential velocity required to maintain a circular orbit. At LEO (~400 km): approximately 7.66 km/s. The 'perpetual free-fall' speed.",
        "definition_es": "Velocidad tangencial necesaria para mantener una órbita circular. En LEO (~400 km): aproximadamente 7.66 km/s. La velocidad de 'caída libre perpetua'.",
        "symbol": "v_orb = √(GM/r)",
        "unit": "km/s",
        "related": ["Circular Orbit", "Gravitational Parameter", "Free Fall", "Orbital Period"]
    },
    {
        "en": "Escape Velocity",
        "es": "Velocidad de Escape",
        "domain": "astrodynamics",
        "entity_type": "PARAMETER",
        "definition_en": "Minimum velocity needed to escape a gravitational field without further propulsion. From Earth's surface: 11.2 km/s.",
        "definition_es": "Velocidad mínima necesaria para escapar de un campo gravitatorio sin propulsión adicional. Desde la superficie terrestre: 11.2 km/s.",
        "symbol": "v_esc = √(2GM/r)",
        "unit": "km/s",
        "related": ["Orbital Velocity", "Gravitational Parameter", "Hyperbolic Orbit", "Interplanetary"]
    },
    {
        "en": "Microgravity",
        "es": "Microgravedad",
        "domain": "astrodynamics",
        "entity_type": "FLIGHT_PHENOMENON",
        "definition_en": "State where gravitational effects are neutralized by free-fall acceleration. NOT absence of gravity — gravity at ISS is ~90% of surface value.",
        "definition_es": "Estado donde los efectos gravitatorios se neutralizan por la aceleración de la caída libre. NO es ausencia de gravedad — la gravedad en la ISS es ~90% del valor superficial.",
        "symbol": "g_eff ≈ 0",
        "unit": "m/s²",
        "related": ["Free Fall", "Weightlessness", "ISS", "Orbital Mechanics"]
    },

    # ══════════════════════════════════════════════════════════
    # PROPULSION — PROPULSIÓN
    # ══════════════════════════════════════════════════════════
    {
        "en": "Turbofan Engine",
        "es": "Motor Turbofán",
        "domain": "propulsion",
        "entity_type": "VEHICLE_TYPE",
        "definition_en": "Jet engine where a large fan bypasses part of the intake air around the core engine, improving fuel efficiency (high-bypass ratio = high efficiency).",
        "definition_es": "Motor a reacción donde un gran ventilador desvía parte del aire de entrada alrededor del núcleo del motor, mejorando la eficiencia de combustible (alta relación de derivación = alta eficiencia).",
        "symbol": "—",
        "unit": "—",
        "related": ["Bypass Ratio", "Specific Fuel Consumption", "Brayton Cycle", "Turbofan"]
    },
    {
        "en": "Bypass Ratio",
        "es": "Relación de Derivación",
        "domain": "propulsion",
        "entity_type": "PARAMETER",
        "definition_en": "Ratio of bypass airflow to core engine airflow. Modern high-bypass engines (BPR > 8) are significantly more fuel-efficient than early turbojets (BPR ~0).",
        "definition_es": "Relación entre el flujo de aire de derivación y el flujo del núcleo del motor. Los modernos motores de alta derivación (BPR > 8) son significativamente más eficientes en combustible que los primeros turborreactores (BPR ~0).",
        "symbol": "BPR",
        "unit": "dimensionless",
        "related": ["Turbofan", "Specific Fuel Consumption", "Thrust", "Propulsive Efficiency"]
    },

    # ══════════════════════════════════════════════════════════
    # FLIGHT REGIMES — REGÍMENES DE VUELO
    # ══════════════════════════════════════════════════════════
    {
        "en": "Subsonic",
        "es": "Subsónico",
        "domain": "aeronautics",
        "entity_type": "FLIGHT_REGIME",
        "definition_en": "Flight regime where Mach number < 0.8. Incompressible flow approximation valid. Standard commercial aviation regime.",
        "definition_es": "Régimen de vuelo donde el número de Mach < 0.8. Aproximación de flujo incompresible válida. Régimen de la aviación comercial estándar.",
        "symbol": "M < 0.8",
        "unit": "—",
        "related": ["Transonic", "Mach Number", "Incompressible Flow", "Commercial Aviation"]
    },
    {
        "en": "Hypersonic",
        "es": "Hipersónico",
        "domain": "aeronautics",
        "entity_type": "FLIGHT_REGIME",
        "definition_en": "Flight regime where Mach number > 5. Air ionizes forming plasma; Navier-Stokes alone insufficient — requires MHD (magnetohydrodynamics). Future of high-speed travel.",
        "definition_es": "Régimen de vuelo donde el número de Mach > 5. El aire se ioniza formando plasma; Navier-Stokes solo es insuficiente — se requiere MHD (magnetohidrodinámica). Futuro del transporte de alta velocidad.",
        "symbol": "M > 5",
        "unit": "—",
        "related": ["Plasma", "MHD", "Shock Wave", "Reentry", "Thermal Protection System"]
    },
]

# ══════════════════════════════════════════════════════════════════════
# ENTITY TYPE DESCRIPTIONS
# ══════════════════════════════════════════════════════════════════════
ENTITY_TYPES = {
    "EQUATION":           "Mathematical expression defining a physical relationship",
    "PARAMETER":          "Measurable variable in aerodynamic or astrodynamic analysis",
    "PHYSICAL_LAW":       "Fundamental principle governing physical behavior",
    "PHYSICAL_CONSTANT":  "Fixed physical quantity (g, R, sigma, etc.)",
    "FORCE":              "Aerodynamic or gravitational force vector",
    "COMPONENT":          "Physical part of an aircraft or spacecraft",
    "VEHICLE_TYPE":       "Category or specific model of aircraft/spacecraft",
    "FLIGHT_PHENOMENON":  "Observable flight behavior or condition",
    "FLIGHT_REGIME":      "Speed/altitude classification (subsonic, hypersonic, etc.)",
    "MANEUVER":           "Deliberate flight or orbital trajectory change",
    "ORBITAL_ELEMENT":    "Keplerian parameter describing orbit shape/orientation",
    "ORBIT_TYPE":         "Classification of orbital trajectory",
    "FLUID_CONCEPT":      "Concept from fluid mechanics",
    "METHODOLOGY":        "Analytical or computational method",
    "MATERIAL":           "Aerospace structural or thermal material",
}

# ══════════════════════════════════════════════════════════════════════
# DOMAIN DESCRIPTIONS
# ══════════════════════════════════════════════════════════════════════
DOMAINS = {
    "aeronautics":    "Atmospheric flight — vehicles operating within Earth's atmosphere",
    "astrodynamics":  "Spaceflight — orbital mechanics and interplanetary trajectories",
    "propulsion":     "Engine systems — atmospheric and space propulsion technologies",
    "materials":      "Structural and thermal materials for aerospace applications",
    "avionics":       "Electronic systems — navigation, communication, flight management",
}


def search_glossary(query: str, domain: str = None, entity_type: str = None) -> list:
    """
    Search the glossary by term, domain, or entity type.
    
    Args:
        query: Search string (matches EN or ES terms)
        domain: Filter by domain (aeronautics, astrodynamics, propulsion, materials, avionics)
        entity_type: Filter by entity type (EQUATION, PARAMETER, PHYSICAL_LAW, etc.)
    
    Returns:
        List of matching glossary entries
    """
    results = []
    query_lower = query.lower()
    
    for entry in GLOSSARY:
        # Text match
        text_match = (
            query_lower in entry["en"].lower() or
            query_lower in entry["es"].lower() or
            query_lower in entry.get("definition_en", "").lower() or
            query_lower in entry.get("symbol", "").lower()
        )
        
        # Domain filter
        domain_match = (domain is None) or (entry["domain"] == domain)
        
        # Entity type filter
        type_match = (entity_type is None) or (entry["entity_type"] == entity_type)
        
        if text_match and domain_match and type_match:
            results.append(entry)
    
    return results


def get_term_by_en(english_term: str) -> dict:
    """Look up a term by its English name."""
    for entry in GLOSSARY:
        if entry["en"].lower() == english_term.lower():
            return entry
    return None


def get_term_by_es(spanish_term: str) -> dict:
    """Look up a term by its Spanish name."""
    for entry in GLOSSARY:
        if entry["es"].lower() == spanish_term.lower():
            return entry
    return None


def get_by_domain(domain: str) -> list:
    """Get all terms for a specific domain."""
    return [e for e in GLOSSARY if e["domain"] == domain]


def get_by_entity_type(entity_type: str) -> list:
    """Get all terms of a specific entity type."""
    return [e for e in GLOSSARY if e["entity_type"] == entity_type]


if __name__ == "__main__":
    # Quick demo
    print(f"\n{'═'*60}")
    print(f"  AEROSCIENTIA — Bilingual Glossary")
    print(f"  Total terms: {len(GLOSSARY)}")
    print(f"{'═'*60}\n")

    # Show by domain
    for domain in DOMAINS:
        terms = get_by_domain(domain)
        print(f"  {domain.upper():20} → {len(terms):3} terms")

    print(f"\n{'─'*60}")
    print("  Search demo: 'lift'")
    print(f"{'─'*60}")
    results = search_glossary("lift")
    for r in results[:3]:
        print(f"  EN: {r['en']}")
        print(f"  ES: {r['es']}")
        print(f"  Type: {r['entity_type']} | Domain: {r['domain']}")
        print()
